version: '2'
services:
  db:
    image: evalsoft/mysql5.7-min-memory
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./.data/wordpress:/var/www/html"
    links:
      - db
    ports:
      - "{{{publicport}}}:80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
